
import { Activity, Armchair } from "lucide-react";

export default function EmgSensorPage() {
  return (
    <div className="bg-background text-foreground">
        <div className="container mx-auto px-4 md:px-6 py-16 md:py-24">
            <section className="max-w-4xl mx-auto">
                <div className="text-center mb-12">
                    <h1 className="text-4xl md:text-5xl font-headline font-bold mb-4">
                        EMG (Electromyography) Sensor
                    </h1>
                    <p className="text-lg text-muted-foreground">
                        How can we detect the hidden electrical signals our brain sends to our muscles? An EMG sensor acts as a listener, allowing us to measure muscle activity and use it to control machines.
                    </p>
                </div>

                <div className="space-y-12">
                    <div>
                        <h2 className="flex items-center gap-2 text-2xl font-headline font-bold mb-4">
                            <Activity className="text-accent" />
                             How It Works: Capturing Muscle Signals
                        </h2>
                        <div className="text-muted-foreground space-y-4">
                            <p>An EMG sensor measures the electrical potential generated by muscle cells when these cells are neurologically activated.</p>
                             <ol className="list-decimal list-inside space-y-2 text-muted-foreground">
                                <li><strong>Detection:</strong> When you decide to move a muscle, your brain sends an electrical signal down your nerves to the muscle fibers. This causes a change in electrical potential across the muscle. Surface EMG sensors use electrodes placed on the skin over the muscle to detect these tiny voltage differences.</li>
                                <li><strong>Conversion:</strong> The raw EMG signal is very small (microvolts to millivolts) and mixed with noise. The sensor module performs several critical signal processing steps:
                                    <ul className="list-disc list-inside pl-4 mt-2">
                                        <li><strong>Amplification:</strong> The weak signal is boosted thousands of times.</li>
                                        <li><strong>Filtering:</strong> Filters are used to remove noise and isolate the frequency band where muscle signals occur.</li>
                                        <li><strong>Rectification:</strong> The AC-like EMG signal is converted to a DC signal that only has positive values.</li>
                                        <li><strong>Smoothing/Integration:</strong> The rectified signal is smoothed to produce a clean waveform where the amplitude corresponds to the level of muscle contraction.</li>
                                    </ul>
                                </li>
                                <li><strong>Output:</strong> The sensor provides an analog output voltage that is proportional to the amount of muscle activity. A flexed muscle produces a high voltage, while a relaxed muscle produces a low voltage.</li>
                            </ol>
                        </div>
                    </div>

                    <div>
                        <h2 className="flex items-center gap-2 text-2xl font-headline font-bold mb-4">
                            <Armchair className="text-accent" />
                            Common Applications
                        </h2>
                        <ul className="list-disc list-inside text-muted-foreground space-y-2">
                            <li><strong>Prosthetics:</strong> Allowing amputees to control robotic limbs by flexing the remaining muscles in their arm or leg.</li>
                            <li><strong>Human-Computer Interfaces:</strong> Creating controllers for games or computers that are operated by muscle contractions.</li>
                            <li><strong>Robotics:</strong> Controlling a robotic arm or gripper by mirroring the user's own muscle movements.</li>
                            <li><strong>Medical & Sports Science:</strong> Analyzing muscle fatigue, activation patterns, and rehabilitation progress.</li>
                        </ul>
                    </div>
                </div>
            </section>
        </div>
    </div>
  );
}

    