
import { Activity, HeartPulse } from "lucide-react";

export default function EcgSensorPage() {
  return (
    <div className="bg-background text-foreground">
        <div className="container mx-auto px-4 md:px-6 py-16 md:py-24">
            <section className="max-w-4xl mx-auto">
                <div className="text-center mb-12">
                    <h1 className="text-4xl md:text-5xl font-headline font-bold mb-4">
                        ECG Sensor (AD8232)
                    </h1>
                    <p className="text-lg text-muted-foreground">
                        How can we see the actual electrical signals that make our heart beat? An ECG (Electrocardiogram) sensor like the AD8232 allows us to capture and visualize the heart's electrical activity.
                    </p>
                </div>

                <div className="space-y-12">
                    <div>
                        <h2 className="flex items-center gap-2 text-2xl font-headline font-bold mb-4">
                            <Activity className="text-accent" />
                             How It Works: Listening to Electrical Whispers
                        </h2>
                        <div className="text-muted-foreground space-y-4">
                            <p>The AD8232 is a specialized signal conditioning block for ECG and other biopotential measurement applications. It's designed to extract, amplify, and filter the tiny electrical signals from the heart.</p>
                             <ol className="list-decimal list-inside space-y-2 text-muted-foreground">
                                <li><strong>Detection:</strong> Three electrodes are placed on the body. These electrodes pick up the very small electrical signals generated by the depolarization and repolarization of the heart muscle during each heartbeat.</li>
                                <li><strong>Conversion:</strong> The raw signal from the body is extremely noisy and small. The AD8232 chip performs several critical steps:
                                    <ul className="list-disc list-inside pl-4 mt-2">
                                        <li><strong>Amplification:</strong> It uses an instrumentation amplifier to significantly boost the weak ECG signal.</li>
                                        <li><strong>Filtering:</strong> It employs high-pass and low-pass filters to remove noise from muscle movement (EMG), 50/60Hz mains interference, and other sources, isolating the desired ECG waveform.</li>
                                        <li><strong>Right Leg Drive (RLD):</strong> A third electrode is used to actively cancel out common-mode interference, which is noise that appears on both measurement electrodes simultaneously.</li>
                                    </ul>
                                </li>
                                <li><strong>Output:</strong> The module outputs a clean, amplified analog signal that represents the classic ECG waveform (with its P-wave, QRS complex, and T-wave). This can be plotted or further analyzed by a microcontroller.</li>
                            </ol>
                        </div>
                    </div>

                    <div>
                        <h2 className="flex items-center gap-2 text-2xl font-headline font-bold mb-4">
                            <HeartPulse className="text-accent" />
                            Common Applications
                        </h2>
                        <ul className="list-disc list-inside text-muted-foreground space-y-2">
                            <li><strong>Portable ECG Monitors:</strong> For fitness and wellness applications, allowing users to view their heart's electrical activity.</li>
                            <li><strong>Medical Research & Education:</strong> As a tool for teaching students about cardiac physiology.</li>
                            <li><strong>Bio-feedback Projects:</strong> Creating systems that react to changes in heart rate variability or other ECG parameters.</li>
                        </ul>
                         <p className="mt-4 text-muted-foreground border-l-4 border-accent pl-4"><strong>Disclaimer:</strong> While sensors like the AD8232 are great for educational and fitness purposes, they are not medical devices and should not be used for diagnosis or treatment of any health condition.</p>
                    </div>
                </div>
            </section>
        </div>
    </div>
  );
}

    