
import { AlertCircle, Package } from "lucide-react";

export default function ShockSensorPage() {
  return (
    <div className="bg-background text-foreground">
        <div className="container mx-auto px-4 md:px-6 py-16 md:py-24">
            <section className="max-w-4xl mx-auto">
                <div className="text-center mb-12">
                    <h1 className="text-4xl md:text-5xl font-headline font-bold mb-4">
                        Shock Sensor
                    </h1>
                     <p className="text-lg text-muted-foreground">
                        How can a package report if it's been dropped? How does a car alarm know that it's been hit? They use a shock sensor, a device specifically designed to detect sudden, sharp impacts.
                    </p>
                </div>

                <div className="space-y-12">
                    <div>
                        <h2 className="flex items-center gap-2 text-2xl font-headline font-bold mb-4">
                            <AlertCircle className="text-accent" />
                             How It Works: Detecting Sudden Impacts
                        </h2>
                         <div className="text-muted-foreground space-y-4">
                            <p>A shock sensor works much like a vibration sensor, but it is typically calibrated to ignore small, continuous vibrations and only react to sharp, high-G impacts.</p>
                             <ol className="list-decimal list-inside space-y-2 text-muted-foreground">
                                <li><strong>Detection:</strong> Many shock sensors use a piezoelectric element. This is a type of crystal that generates a voltage when it is physically stressed or deformed. A sudden impact causes a sharp deformation of the crystal.</li>
                                <li><strong>Conversion:</strong> The deformation of the piezoelectric crystal generates a brief, but relatively high, voltage spike. This is different from the continuous, low-level signals that might be generated by normal vibration.</li>
                                <li><strong>Output:</strong> The sensor's circuitry includes a comparator that checks if this voltage spike exceeds a pre-set threshold. If it does, the sensor outputs a digital signal to indicate that a shock event has occurred.</li>
                            </ol>
                            <p className="border-l-4 border-accent pl-4 text-foreground">Other shock sensors might use a mechanical switch, similar to a vibration sensor, but with a stiffer spring or heavier mass that only breaks contact during a strong impact.</p>
                        </div>
                    </div>

                    <div>
                        <h2 className="flex items-center gap-2 text-2xl font-headline font-bold mb-4">
                            <Package className="text-accent" />
                            Common Applications
                        </h2>
                        <ul className="list-disc list-inside text-muted-foreground space-y-2">
                            <li><strong>Vehicle Alarms:</strong> To detect the impact from a collision or a break-in attempt, often triggering a "warn-away" chirp for light impacts and a full alarm for heavy ones.</li>
                            <li><strong>Shipping and Logistics:</strong> Devices like "ShockLog" or "Tip-N-Tell" are placed in sensitive shipments to provide a visual or digital record if the package was dropped or mishandled.</li>
                            <li><strong>Industrial Machinery:</strong> To detect sudden impacts that could indicate a catastrophic failure or a crash, triggering an emergency stop.</li>
                             <li><strong>Data Storage:</strong> Some hard drives use shock sensors to quickly park the read/write heads during a fall to prevent data loss upon impact.</li>
                        </ul>
                    </div>
                </div>
            </section>
        </div>
    </div>
  );
}
